---
options:
  peers:
    type: string
    default: ""
    description: |
      base64 yaml file with peer options
      See include-base64://
      Availabel options
        * allowedips - the allowed ip ranges for this peer
        * publickey - the public key
        * endpoint - peer ip and port X.X.X.X:PORT
        * persistentkeepalive - optional keep alive in seconds
  listen-port:
    type: int
    default: 15820
    description: "UDP port to listen for peers on"
  address:
    type: string
    default: "10.10.10.1/24"
    description: "Interface address"
  forward-ip:
    type: boolean
    default: true
    description: "Forward packets for clients"
  forward-dev:
    type: string
    default: "eth0"
    description: "Device to forward packets on"
  proxy-via-hostname:
    type: boolean
    default: false
    description: "If true use fqdn with the reverse proxy, else use ip address"
  private-key:
    type: string
    default: ""
    description: "Specify rather than generating a private key, base64 encoded"
# Is this even used, what was it meant for?
#  endpoint:
#    type: string
#    default: ""
#    description: "Public endpoint address and port"
