#!/usr/local/sbin/charm-env python3

from libwireguard import WireguardHelper
from charmhelpers.core import hookenv

helper = WireguardHelper()
key, ip, port = helper.get_settings()
hookenv.action_set({'key': key,
		    'ip': ip,
		    'port': port,
		    })
